### ISSUE TITLE
[Help Wanted] - Generating chord progressions

### ISSUE THREAD

**Issue by gildurao** [Rainbow-Dreamer/sf2_loader#10]
Hello 👋 ,

I've been able to generate 1 voice melodies so far with ease, but right now I am struggling to export a piece that is supposed to represent a chord progression.

I have this code that generates the progression:

```python
def chord_progression_parsing(output, scaleRoot, scaleMode, durations, volume=100):
    scale = mp.scale(scaleRoot, scaleMode)
    progression = []
    degree = 1
    numberOfNotes = 3
    for i in range(len(output)):
        currentSymbol = output[i]
        duration = random.choice(durations)
        chord = scale.pickchord_by_degree(
            degree, duration=duration, num=numberOfNotes)
        for j in range(1, len(output)):
                #some conditions to know when to create a new chord that dont have musicpy code
                duration = random.choice(durations)
                chordNotes = chord.notes
                progressionChord.append(
                    mp.chord(chordNotes, interval=1, duration=duration))
                chord = scale.pickchord_by_degree(
                    degree, duration=duration, num=numberOfNotes)
               # conditions  to change degree and numberOfNotes values that don't have musicpy code
    print(progressionChord)
    return [progressionChord]
```

And then I am using export_piece like this

```python
  piece = sf.mp.piece(
            [progressionChord], [sf2.current_preset_num], bpm, [0], channels=[1]
        )
````

But I get this error

```
Traceback (most recent call last):
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic\lib\yourscript.py", line 196, in <module>
    generate_music(lSystem, iterations, musicalParsing, scale, musicKey, bpm,
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic\lib\yourscript.py", line 163, in generate_music
    sf2.export_piece(
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\.venv\lib\site-packages\sf2_loader\read_sf2\read_sf2.py", line 656, in export_piece
    current_chord.normalize_tempo()
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\.venv\lib\site-packages\musicpy\structures.py", line 3360, in normalize_tempo      
    first_track.normalize_tempo(bpm, start_time=first_track_start_time)
AttributeError: 'list' object has no attribute 'normalize_tempo'
```

Could you tell me what I am doing wrong if you would be so kind?

**Comment by Rainbow-Dreamer** [comment]
You're welcome :) By the way, recently there are some big updates of musicpy and sf2_loader, which includes some critical bug fixes, so I recommend you to upgrade both of them to the latest version, thanks.
