### ISSUE TITLE
Installation on Linux fails when processing MIDIUtil package

### ISSUE THREAD

**Issue by gildurao** [Rainbow-Dreamer/sf2_loader#3]
Hello :wave: ,

Per your documentation in the README, I downloaded the Linux compatible dist of sf2_loader, but when running the script, this error pops up:

```
Installed /usr/local/lib/python3.8/dist-packages/mido-1.2.10-py3.8.egg
Searching for midiutil
Reading https://pypi.org/simple/midiutil/
Downloading https://files.pythonhosted.org/packages/f5/44/fde6772d8bfaea64fcf5eb948124d0a5fdf5f848b14ac22a23ced53e562d/MIDIUtil-1.2.1.tar.gz#sha256=79fa983bd1efc60785f68a8fe78fa8f45b8d7ec5898bf7cb7f3f7f3336d6a90a
Best match: MIDIUtil 1.2.1
Processing MIDIUtil-1.2.1.tar.gz
Writing /tmp/easy_install-5xx501gk/MIDIUtil-1.2.1/setup.cfg
Running MIDIUtil-1.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5xx501gk/MIDIUtil-1.2.1/egg-dist-tmp-f8y0q5s4
warning: no previously-included files matching '*' found under directory 'build'
warning: no previously-included files matching '*' found under directory 'dist'
warning: no previously-included files matching '*.pyc' found under directory '.'
warning: no previously-included files matching '__pycache__' found under directory '.'
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-5xx501gk/MIDIUtil-1.2.1/setup.py", line 7, in <module>
    license='GPLv3',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(name='sf2_loader',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 450, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 740, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 784, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 781, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 712, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 738, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 923, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1191, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-5xx501gk/MIDIUtil-1.2.1/setup.py", line 7, in <module>
    license='GPLv3',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

Up until this point installation was going fine without errors

**Comment by Rainbow-Dreamer** [comment]
That's weird, I can install midiutil using pip on python 3.8.11 in Ubuntu 18.04.5 with no problems. Could you run `pip install midiutil` separately in terminal and see what it gets?

**Comment by Rainbow-Dreamer** [comment]
Well, it seems that when you use `python setup.py install` to install this package on Linux, pip will try to install MIDIUtil which is a reuqired package of musicpy, but it seems it automatically found a corrupted version, so it results like this. You can simply download the latest version of MIDIUtil by running `pip install midiutil` in the terminal, and then you can running `python setup.py install` again, this time you will get the package installed. I will add this to the instructions in readme for sure. Thanks for your feedback :)

**Comment by gildurao** [comment]
I managed to install it separately and went successfully. I should warn though, at least in my Ubuntu machine, running ``sudo pip install`` or just ``pip install`` installed the packages in different folders, which resulted in some mistakes that I had to debug.

I should also note that I was able to install sf2_loader using pip just fine. So I think there might not be a need to install it in a different way?

**Comment by Rainbow-Dreamer** [comment]
There's actually a reason for that, when you try to pip install this package on some Linux systems (at least for my testing), the pip install for simpleaudio will fails due to gcc compile errors even if you have already installed the linux dependencies, this will actually terminate the whole install process and result a fail installation of this package, so I remove the install requires of simpleaudio in `setup.py` for the linux compatible versions, and then you can try to install simpleaudio separately, while this package could be installed. I can add some changes to readme, if pip works, then go with it, otherwise use `python setup.py install`.

**Comment by gildurao** [comment]
I like that idea of showing both options in the README. I think you can close this issue

**Comment by Rainbow-Dreamer** [comment]
Thanks for your feedback :)

**Comment by Rainbow-Dreamer** [comment]
Well, I forgot one important thing, the codes for Linux and macOS compatible versions are partly changed for compatibility, so it is actually necessary to download them from release page and run `python setup.py install` to install this package, otherwise some of the functionalities won't functioning normally on Linux and macOS.
