### ISSUE TITLE
sf2.export_midi_file fails

### ISSUE THREAD

**Issue by gildurao** [Rainbow-Dreamer/sf2_loader#9]
Hello 👋 ,

Today I tried to export a piece to a midi file, but I am facing the following errors from musicpy and midifiles.

```
Traceback (most recent call last):
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\musicpy\musicpy.py", line 317, in read
    current_midi = midi(name)
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\mido\midifiles\midifiles.py", line 323, in __init__
    with io.open(filename, 'rb') as file:
TypeError: expected str, bytes or os.PathLike object, not piece

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic\lib\yourscript.py", line 176, in <module>
    generate_music(lSystem, iterations, musicalParsing, scale, musicKey, bpm,
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic\lib\yourscript.py", line 145, in generate_music
    sf2.export_midi_file(
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\read_sf2\read_sf2.py", line 739, in export_midi_file
    current_chord = mp.read(current_chord,
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\musicpy\musicpy.py", line 319, in read
    current_midi = midi(file=riff_to_midi(name))
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\musicpy\musicpy.py", line 3598, in riff_to_midi
    root = chunk.Chunk(riff_name, bigendian=False)
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\chunk.py", line 61, in __init__
    self.chunkname = file.read(4)
AttributeError: 'piece' object has no attribute 'read'
```

Here is the python code with the export midi call

```python
sf2.export_midi_file(
        piece, name=rf"{defaultPath}\generated_music.mid")
```

The variable ``piece`` is correct because I can generate .wav files correctly.

Output of ```pip list```:

```
PS C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic> pip list
Package     Version
----------- -------
autopep8    1.5.7
keyboard    0.13.5
MIDIUtil    1.2.1
mido        1.2.10
mpu         0.23.1
musicpy     4.24
numpy       1.21.2
Pillow      8.3.2
pip         21.2.3
py          1.10.0
pycodestyle 2.7.0
pydub       0.25.1
pygame      2.0.1
pyglet      1.5.11
setuptools  57.4.0
sf2-loader  0.59
simpleaudio 1.0.4
toml        0.10.2
```

Output of ```python --version```
```
PS C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic> python --version
Python 3.9.7
```

**Comment by Rainbow-Dreamer** [comment]
You're welcome :)
